October 2023 news update
oobecomau/theblueprint pull request #13
Opened 2023-10-11 07:08 UTC by martincaddick

october2023newsupdate.md and updated index.md files

2023-10-11 07:08 UTC, martincaddick commented
@mattshawoobe @SamBH Please review

2023-10-15 22:33 UTC, SamBH commented on docs/news/october2023newsupdate.md
Please can we make typos point 4 (as least exciting). Also, missing space in 'AzureAD'

2023-10-15 22:34 UTC, SamBH requested changes
Please see comment in new article.

2023-10-15 22:41 UTC, martincaddick commented on docs/news/october2023newsupdate.md
Changed order and fixed AzureAD

2023-11-13 02:47 UTC, SamBH approved these changes

2023-11-13 02:47 UTC, merged