Windows Information Protection sunset
oobecomau/theblueprint pull request #14
Opened 2023-11-20 05:52 UTC by martincaddick

Added news article about Windows Information Protection sunset. Added notes where WIP is mentioned in ABACs and designs to refer back to the news article.

Additional information to be added in future re:
1. Conditional Access + session controls using Microsoft Defender for Cloud Apps
2. Using Windows MAM (Only for unmanaged devices)
3. Leverage Tenant Restrictions to manage how SaaS and LOB applications are accessed
4. Leverage Endpoint DLP to define work vs non-work data boundaries

2023-11-20 06:05 UTC, martincaddick reviewed
Viewed all pages and checked all links

2023-11-20 06:11 UTC, martincaddick reviewed
All files reviewed

2023-12-04 01:36 UTC, oobemlr commented on docs/as-built-as-configured/hybrid-task-sequence.md
> +AutopilotConfigurationFile.json | The AutopilotConfigurationFile.json is required to be available within an Microsoft Endpoint Configuration Manager (MECM) package. As a requirement the [Intune enrol
gtg

2023-12-04 05:47 UTC, martincaddick commented on docs/news/index.md
> +| [**Novemeber 2023 Update**<br><em>13 Nov 2023</em><br>Windows Information Protection sunset](../news/wip-guidance-2023-11-13.md) |
@oobemlr This has a typo in it

2023-12-07 02:46 UTC, SamBH requested changes
Please update as per comments.

2023-12-07 02:46 UTC, SamBH commented on docs/news/wip-guidance-2023-11-13.md
> +
For consistency, we should have a comma and or after point 2, and finish point 3 with a full stop.

2023-12-07 02:46 UTC, SamBH commented on docs/news/wip-guidance-2023-11-13.md
> +
Suggest rewording to the following:

For all new blueprint deployments, we recommend using the alternative products/features listed below. More information on how to configure these is planned to be published in early 2024.

2023-12-07 02:46 UTC, SamBH commented on docs/news/wip-guidance-2023-11-13.md
> +
Entra ID not Azure AD, please. Also lowercase p in planned for consistency.

2023-12-07 02:46 UTC, SamBH commented on docs/news/index.md
> +| [**Novemeber 2023 Update**<br><em>13 Nov 2023</em><br>Windows Information Protection sunset](../news/wip-guidance-2023-11-13.md) |
Pending update

2023-12-07 02:54 UTC, martincaddick commented on docs/news/wip-guidance-2023-11-13.md
> +
added , or to the second option

2023-12-07 02:59 UTC, martincaddick commented on docs/news/wip-guidance-2023-11-13.md
> +
Fixed

2023-12-07 04:23 UTC, martincaddick reviewed
Sam these are all resolved.

2023-12-07 23:58 UTC, SamBH approved these changes

2023-12-07 23:58 UTC, merged